### PR TITLE
Add db seeding script

### PR DESCRIPTION
**Pull request by anoadragon453**
Adds a script to initially seed the database with proposal labels so specs-bot can operate on an existing spec repo with very little friction.

Works via `insert or replace`, so can be run multiple times without worrying about duplication occurring.

### CODE REVIEW

**Comment by anoadragon453** [comment]
Added a requirements.txt for ease of use.

**Review by GordonF42 — COMMENTED** [review]
Thanks @anoadragon453  :)
I'll let @vabd do the testing, but I can see two minor things:
1. I'd move the script & requirements.txt to  scripts/fill-db/ to ease future script additions (with different requirements.txt)
2. the .py file is not executable, even though there is a shebang

**Comment by anoadragon453** [comment]
Great points, thank you. I've done as you've asked.

**Review by vabd — CHANGES_REQUESTED** [review]
Hey @anoadragon453, and thanks! Works well and easily from my end. I'm just going to ask you to mention that the script is exclusive to sqlite3 (maybe by appending a "(only for sqlite3 databases)" or something like that to the script's title), because the bot supports both sqlite3 and postgresql, otherwise it's good to go!

**Comment by anoadragon453** [comment]
Done and done.

**Comment by anoadragon453** [comment]
and done

**Review by vabd — APPROVED** [review]
Awesome, I'm merging it, thanks again!

**Pull request merged**
